version: "3.9"

services:
    ignite_database:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=senha
            - POSTGRES_DB=ignite
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: "rentxapicontainerd"
        ports:
            - 3333:3333
        volumes:
            - .:/usr/api
        links:
            - ignite_database
        depends_on:
            - ignite_database

volumes:
    pgdata:
        driver: local
